name: "ReSharper Analysis"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: JetBrains ReSharper Inspect Code
      uses: JetBrains/ReSharper-InspectCode@v0.12
